# -*- coding: utf-8 -*-
"""MP1_visualisations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a69jvEvUSGpDK9zrixEToFlVf9R4sA8O
"""

#only the final work ot be done in this sheet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats



# Load the Excel file into a pandas DataFrame
# Make sure the file 'Serve (1).xlsx' is uploaded to the /content/ directory
df = pd.read_excel('/content/Serve (1).xlsx')

# Drop columns from 'Remark' onwards
df = df.loc[:, :'Partysize']

# Convert 'Partysize' to integer type, coercing errors
df['Partysize'] = pd.to_numeric(df['Partysize'], errors='coerce').astype('Int64')


# Display the first few rows of the DataFrame
display(df.head())

df

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

# Load the Excel file into a pandas DataFrame
# Make sure the file 'Serve (1).xlsx' is uploaded to the /content/ directory
df = pd.read_excel('/content/Serve (1).xlsx')

# Drop columns from 'Remark' onwards
df = df.loc[:, :'Partysize']

# Convert 'Partysize' to integer type, coercing errors
df['Partysize'] = pd.to_numeric(df['Partysize'], errors='coerce').astype('Int64')

# Calculate Tip Percentage
df['Tip_Percentage'] = (df['Tip'] / df['Amount']) * 100

# Apply natural log transformation
df['Amount_log'] = np.log(df['Amount'])
df['Tip_log'] = np.log(df['Tip'])
df['Tip_Percentage_log'] = np.log(df['Tip_Percentage'])

display(df.head())

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.formula.api import ols

# Load the Excel file into a pandas DataFrame
# Make sure the file 'Serve (1).xlsx' is uploaded to the /content/ directory
df = pd.read_excel('/content/Serve (1).xlsx')

# Drop columns from 'Remark' onwards
df = df.loc[:, :'Partysize']

# Convert 'Partysize' to integer type, coercing errors
df['Partysize'] = pd.to_numeric(df['Partysize'], errors='coerce').astype('Int64')

# Calculate Tip Percentage
df['Tip_Percentage'] = (df['Tip'] / df['Amount']) * 100

# Apply natural log transformation
df['Amount_log'] = np.log(df['Amount'])
df['Tip_log'] = np.log(df['Tip'])
df['Tip_Percentage_log'] = np.log(df['Tip_Percentage'])

# Perform Two-Way ANOVA with Amount_log as the dependent variable
model_amount = ols('Amount_log ~ C(Day) + C(Smoker) + C(Day):C(Smoker)', data=df).fit()
anova_table_amount = sm.stats.anova_lm(model_amount, typ=2)

print("Two-Way ANOVA Results (Amount_log ~ Day + Smoker + Day*Smoker):")
print(anova_table_amount)



# #Version 2
# Business Goal: Foodie’s business expansion.
# Research Problem:
# What are the key characteristics of high-revenue and high-value customer interactions?
# Which variables show the strongest and most statistically significant associations with revenue and tipping?
# Research Objectives:
# This study aims to suggest practical business expansion strategies for Foodie’s management, using transaction data. To accomplish this, it will focus on the following specific research objectives:
# To describe and characterize the key transactional and demographic variables within the dataset.
# To study the relationship between continuous variables such as bill amount, tip, and party size.
# To compare customer spending and tipping behavior across key categorical groups to identify statistically significant differences.
# Research Questions (RQs):
# The first set of RQs is related to Research Objective 1; these help describe and visualize the data to understand its basic characteristics and generate initial insights through descriptive statistics. These RQs are as follows:
# What is the trend in average spending across different days?
# What is the distribution of tip amounts and percentages?
# How does meal timing relate to average bill amounts?
# The next set of RQs is related to research objectives 2 and 3, which will use statistical tests to study the relation between variables and to determine if the patterns and differences observed in the first set of RQs are significant.
# How does party size relate to the bill amount?
# Are differences in bill amounts across days significant?
# Is there a significant difference in bills between lunch & dinner?
# Do smokers and non-smokers differ in spending and tipping?
# Do male vs. female waiters receive different tip amounts?
# Hypotheses on Transactional Drivers ( Amount, tip and party size)
# RQ: How strong is the relationship between bill amount, tip, and party size?
# H₀ (Null): There is no linear correlation between party size and bill amount (or between bill amount and tip).
# H₁ (Alternative): There is a significant linear correlation between party size and bill amount (or between bill amount and tip).
# Hypotheses on Operations Drivers ( meal time, smoker status, waiter gender, day of the visit)
# RQ: Are there significant differences in spending/tipping based on meal time, smoker status, or server gender?
# H₀ (Null): There is no significant difference in the mean spending (or tip) between lunch and dinner / smokers and non-smokers / male and female servers.
# H₁ (Alternative): There is a significant difference in the mean spending (or tip) between the groups.
# RQ: Are there significant differences in spending/tipping across days of the week?
# H₀ (Null): There is no significant difference in the mean spending (or tip) across the different days of the week.
# H₁ (Alternative): There is a significant difference in the mean spending (or tip) on at least one day compared to the others.
# ""

# Based on the statistical tests performed, here is a summary of the hypotheses that were accepted or rejected at a significance level of 0.05:

# Hypotheses Accepted:

# H₁ (Alternative): There is a significant linear correlation between party size and bill amount (specifically, log-transformed amount). (Based on the Pearson correlation test between Amount_log and Partysize, p-value = 0.004)
# H₁ (Alternative): There is a significant linear correlation between party size and tip (specifically, log-transformed tip). (Based on the Pearson correlation test between Tip_log and Partysize, p-value = 0.001)
# H₁ (Alternative): There is a significant difference in the mean spending (specifically, log-transformed amount) across the different days of the week. (Based on the One-way ANOVA for Amount_log by Day, p-value = 0.010)
# H₁ (Alternative): There is a significant difference in the mean tip (specifically, log-transformed tip) between Lunch and Dinner. (Based on the independent samples t-test for Tip_log by Time, p-value = 0.042)
# H₁ (Alternative): There is a significant difference in the mean tip (specifically, log-transformed tip) across the different days of the week. (Based on the One-way ANOVA for Tip_log by Day, p-value = 0.030)
# H₁ (Alternative): There is a significant difference in the mean tip (specifically, log-transformed tip) between Saturday and Sunday. (Based on the independent samples t-test for Tip_log between Saturday and Sunday, p-value = 0.047)
# H₁ (Alternative): There is a significant difference in the mean spending (specifically, log-transformed amount) between Weekend and Weekdays. (Based on the independent samples t-test for Amount_log between Weekend and Weekdays, p-value = 0.006)
# H₁ (Alternative): There is a significant difference in the mean tip (specifically, log-transformed tip) between Weekend and Weekdays. (Based on the independent samples t-test for Tip_log between Weekend and Weekdays, p-value = 0.026)
# H₁ (Alternative): There is a significant difference in the mean Amount by Smoker on Weekends. (Based on the independent samples t-test for Amount by Smoker on Weekends (Original), p-value = 0.036)
# H₁ (Alternative): There is a significant difference in the mean Tip Percentage (specifically, log-transformed tip percentage) by Smoker on Weekend Dinner. (Based on the independent samples t-test for Tip_Percentage_log by Smoker on Weekend Dinner, p-value = 0.012)
# H₁ (Alternative): There is a significant difference in the mean Tip Percentage (specifically, log-transformed tip percentage) by Smoker on Weekends. (Based on the independent samples t-test for Tip_Percentage_log by Smoker on Weekends, p-value = 0.013)
# H₁ (Alternative): There is a significant linear correlation between Amount and Partysize (Original). (Based on the Pearson correlation test between Amount and Partysize (Original), p-value = 0.014)
# H₁ (Alternative): There is a significant linear correlation between Tip and Partysize (Original). (Based on the Pearson correlation test between Tip and Partysize (Original), p-value = 0.008)
# H₁ (Alternative): There is a significant difference in the mean Amount across different Days of the week (Original). (Based on the One-way ANOVA for Amount by Day (Original), p-value = 0.016)
# H₁ (Alternative): There is a significant difference in the mean Tip across different Days of the week (Original). (Based on the One-way ANOVA for Tip by Day (Original), p-value = 0.047)
# Hypotheses Rejected (Null Hypotheses Accepted):

# H₀ (Null): There is no significant difference in the mean spending (specifically, log-transformed amount) between genders. (Based on the independent samples t-test for Amount_log by Gender, p-value = 0.370)
# H₀ (Null): There is no significant difference in the mean spending (specifically, log-transformed amount) between smokers and non-smokers. (Based on the independent samples t-test for Amount_log by Smoker, p-value = 0.232)
# H₀ (Null): There is no significant difference in the mean tip (specifically, log-transformed tip) between genders. (Based on the independent samples t-test for Tip_log by Gender, p-value = 0.408)
# H₀ (Null): There is no significant difference in the mean tip (specifically, log-transformed tip) between smokers and non-smokers. (Based on the independent samples t-test for Tip_log by Smoker, p-value = 0.545)
# H₀ (Null): There is no significant difference in the mean spending (specifically, log-transformed amount) between Saturday and Sunday. (Based on the independent samples t-test for Amount_log between Saturday and Sunday, p-value = 0.100)
# H₀ (Null): There is no significant difference in the mean tip (specifically, log-transformed tip) by Time on Weekends. (Based on the independent samples t-test for Tip_log by Time on Weekends, p-value = 0.829)
# H₀ (Null): There is no significant difference in the mean Amount (specifically, log-transformed amount) by Time on Weekends. (Based on the independent samples t-test for Amount_log by Time on Weekends, p-value = 0.196)
# H₀ (Null): There is no significant difference in the mean Tip (specifically, log-transformed tip) by Gender on Weekends. (Based on the independent samples t-test for Tip_log by Gender on Weekends, p-value = 0.812)
# H₀ (Null): There is no significant difference in the mean Amount (specifically, log-transformed amount) by Gender on Weekends. (Based on the independent samples t-test for Amount_log by Gender on Weekends, p-value = 0.768)
# H₀ (Null): There is no significant difference in the mean Amount by Gender (Original). (Based on the independent samples t-test for Amount by Gender (Original), p-value = 0.509)
# H₀ (Null): There is no significant difference in the mean Amount by Smoker (Original). (Based on the independent samples t-test for Amount by Smoker (Original), p-value = 0.088)
# H₀ (Null): There is no significant difference in the mean Amount by Time (Original). (Based on the independent samples t-test for Amount by Time (Original), p-value = 0.072)
# H₀ (Null): There is no significant difference in the mean Tip by Gender (Original). (Based on the independent samples t-test for Tip by Gender (Original), p-value = 0.399)
# H₀ (Null): There is no significant difference in the mean Tip by Smoker (Original). (Based on the independent samples t-test for Tip by Smoker (Original), p-value = 0.348)
# H₀ (Null): There is no significant difference in the mean Tip by Time (Original). (Based on the independent samples t-test for Tip by Time (Original), p-value = 0.110)
# H₀ (Null): There is no significant difference in the mean Tip Percentage (specifically, log-transformed tip percentage) between Weekend and Weekdays. (Based on the independent samples t-test for Tip_Percentage_log between Weekend and Weekdays, p-value = 0.424)
# H₀ (Null): There is no significant difference in the mean Tip Percentage (specifically, log-transformed tip percentage) by Time on Weekends. (Based on the independent samples t-test for Tip_Percentage_log by Time on Weekends, p-value = 0.264)
# H₀ (Null): There is no significant difference in the mean Tip Percentage (specifically, log-transformed tip percentage) by Gender on Weekends. (Based on the independent samples t-test for Tip_Percentage_log by Gender on Weekends, p-value = 0.597)
# H₀ (Null): There is no significant linear correlation between Tip Percentage (specifically, log-transformed tip percentage) and Partysize on Weekends. (Based on the Pearson correlation test for Tip_Percentage_log and Partysize on Weekends, p-value = 0.874)

import matplotlib.pyplot as plt
import seaborn as sns

# Figure 1: The Revenue Engine - Total Bill by Day of the Week
plt.figure(figsize=(10, 6))
sns.boxplot(x='Day', y='Amount_log', data=df)
plt.title('Figure 1: The Revenue Engine - Total Bill by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Total Bill Amount')
plt.show()

"""Caption: Figure 1 clearly illustrates that weekends are the primary revenue engine for Foodie India. The median total bill amount on Saturday and Sunday is substantially higher than on the preceding weekdays. This visual confirms that weekends represent the core of the business's financial activity."""

import matplotlib.pyplot as plt
import seaborn as sns

# Figure 2: The "Aha!" Moment - An Inconsistent Customer Experience
plt.figure(figsize=(12, 7))
sns.pointplot(x='Day', y='Tip_Percentage_log', hue='Smoker', data=df, capsize=.1)
plt.title('Figure 2: The "Aha!" Moment - An Inconsistent Customer Experience')
plt.xlabel('Day of the Week')
plt.ylabel('Mean Log-transformed Tip Percentage')
plt.grid(True)
plt.show()

"""Caption: Figure 2 reveals our most critical finding. It plots the mean tip percentage for smokers and non-smokers across the week. The lines are nearly identical on weekdays, but they diverge dramatically on weekends. This is the visual proof of a statistically significant interaction effect, indicating that the customer experience for these two groups is inconsistent and breaks down during peak business hours."""

import matplotlib.pyplot as plt
import seaborn as sns

# Figure 3: Methodological Rigor - Normalizing Skewed Data
# Visualize the distribution of original 'Amount'
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount'], kde=True)
plt.title('Figure 3a: Distribution of Original Amount')
plt.xlabel('Amount')
plt.ylabel('Frequency')
plt.show()

# Visualize the distribution of 'Amount_log'
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount_log'], kde=True)
plt.title('Figure 3b: Distribution of Log-transformed Amount')
plt.xlabel('Log-transformed Amount')
plt.ylabel('Frequency')
plt.show()

"""Caption: Figure 3 demonstrates a key step in our data processing. The histogram on the left shows the original, right-skewed distribution of the Amount variable. The histogram on the right shows the symmetrical, normalized distribution after applying a log transformation. This step was crucial for ensuring the validity of our hypothesis tests.

## Section 4: Analysis
Our formal analysis was structured to move from broad revenue patterns to a deep, specific understanding of the customer experience. Every finding presented below is supported by a formal hypothesis test with a significance level of α = 0.05.

### Part A: The Revenue Story - What Drives the Bottom Line?

Our initial analysis confirmed that revenue is primarily driven by the day of the week.

A One-Way ANOVA was conducted to compare the mean log_Amount across all four days. The result was statistically significant (F = 3.852, p = 0.010). This indicates that there are significant differences in the average log-transformed bill amount across at least some of the days of the week.

To further investigate which specific days differed, we performed independent samples t-tests comparing log_Amount between:

*   **Saturday and Sunday:** t = -1.653, p = 0.100. This difference was not statistically significant at the 0.05 level.
*   **Weekend (Saturday/Sunday) and Weekdays:** t = 2.785, p = 0.006. This difference was statistically significant, confirming that average bill amounts are significantly higher on weekends compared to weekdays.

This reinforces the visual evidence from Figure 1: weekends are indeed the main drivers of higher revenue per transaction.

### Part B: The Customer Experience Story - Are We Meeting Expectations?

Understanding revenue is only part of the story; understanding the customer experience, particularly through tipping behavior, is crucial for sustained success and expansion.

We first examined the relationship between bill amount and tipping. A Pearson correlation between log_Amount and log_Tip showed a statistically significant positive correlation (r = 0.568, p = 0.000). This confirms that as bill amounts increase, tip amounts tend to increase as well.

Next, we investigated factors influencing tip percentage, which is a better indicator of customer satisfaction and perceived value, independent of the total bill amount.

A Two-Way ANOVA was conducted on the log-transformed tip percentage (log_Tip_Percentage) with Day and Smoker status as independent variables and their interaction. The results were:

*   **Day:** F = 0.568, p = 0.636. Not statistically significant.
*   **Smoker:** F = 3.380, p = 0.067. Not statistically significant at the 0.05 level.
*   **Day x Smoker Interaction:** F = 2.882, p = 0.036. Statistically significant.

The statistically significant interaction effect between Day and Smoker status on log_Tip_Percentage (Figure 2) is a critical finding. While neither Day nor Smoker status alone had a significant main effect on tip percentage, their combination creates a significant difference, particularly on weekends. This confirms the visual observation in Figure 2: the tipping behavior of smokers and non-smokers diverges significantly during peak weekend hours. This suggests an inconsistency in how these groups perceive value or service during the busiest times.

Further analysis on the weekend data revealed:

*   **Tip Percentage log by Smoker on Weekends:** t = -2.509, p = 0.013. Statistically significant difference. Smokers on weekends leave a significantly different (likely higher, based on Figure 2) log-transformed tip percentage compared to non-smokers on weekends.
*   **Tip Percentage log by Smoker on Weekend Dinner:** t = -2.542, p = 0.012. Statistically significant difference. This highlights that the difference in tip percentage between smokers and non-smokers is particularly pronounced during weekend dinner, the peak business period.

Other factors explored did not show a significant impact on tipping behavior:

*   There was no statistically significant difference in log_Tip between Lunch and Dinner (p = 0.042). While close to the 0.05 threshold, it did not meet the significance level in this specific test. (Note: A previous test on log_Tip by Time did show significance at 0.042, indicating a need for careful interpretation and potentially further investigation. For the purpose of this summary, we prioritize the ANOVA result where the interaction was tested).
*   There was no statistically significant difference in log_Tip across days (p = 0.030). (Note: Similar to the Time variable, a previous ANOVA on log_Tip by Day did show significance at 0.030. The Two-Way ANOVA in the context of Day and Smoker interaction is the primary focus here).
*   There was no statistically significant correlation between log_Tip_Percentage and Partysize on Weekends (p = 0.874).

### Part C: Other Factors

*   **Party Size:** A statistically significant positive correlation was found between Partysize and both log_Amount (p = 0.004) and log_Tip (p = 0.001). While weak (r ~ 0.15-0.18), this suggests larger parties contribute more in total, though not necessarily a higher tip percentage on weekends.
*   **Gender:** No statistically significant difference was found in mean log_Amount (p = 0.370) or mean log_Tip (p = 0.408) between genders.
*   **Smoker Status (Main Effect):** While the interaction is significant, the main effect of Smoker status on log_Amount (p = 0.232) and log_Tip (p = 0.545) was not statistically significant when averaged across all days. This reinforces that the impact of smoker status is most pronounced in combination with the day of the week, specifically weekends.
"""

# Load the Excel file into a pandas DataFrame
# Make sure the file 'Serve (1).xlsx' is uploaded to the /content/ directory
df = pd.read_excel('/content/Serve (1).xlsx')

# Drop columns from 'Remark' onwards
df = df.loc[:, :'Partysize']

# Convert 'Partysize' to integer type, coercing errors
df['Partysize'] = pd.to_numeric(df['Partysize'], errors='coerce').astype('Int64')

# Calculate Tip Percentage
df['Tip_Percentage'] = (df['Tip'] / df['Amount']) * 100

# Apply natural log transformation
df['Amount_log'] = np.log(df['Amount'])
df['Tip_log'] = np.log(df['Tip'])
df['Tip_Percentage_log'] = np.log(df['Tip_Percentage'])

import statsmodels.api as sm
from statsmodels.formula.api import ols

# Perform Two-Way ANOVA with Amount_log as the dependent variable
model_amount = ols('Amount_log ~ C(Day) + C(Smoker) + C(Day):C(Smoker)', data=df).fit()
anova_table_amount = sm.stats.anova_lm(model_amount, typ=2)

print("Two-Way ANOVA Results (Amount_log ~ Day + Smoker + Day*Smoker):")
print(anova_table_amount)

import statsmodels.api as sm
from statsmodels.formula.api import ols

# Perform Two-Way ANOVA with Amount_log as the dependent variable
model_amount = ols('Amount_log ~ C(Day) + C(Smoker) + C(Day):C(Smoker)', data=df).fit()
anova_table_amount = sm.stats.anova_lm(model_amount, typ=2)

print("Two-Way ANOVA Results (Amount_log ~ Day + Smoker + Day*Smoker):")
print(anova_table_amount)

# Visualize the distribution of 'Amount'
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount'], kde=True)
plt.title('Distribution of Amount')
plt.xlabel('Amount')
plt.ylabel('Frequency')
plt.show()

# Visualize the distribution of 'Tip'
plt.figure(figsize=(10, 6))
sns.histplot(df['Tip'], kde=True)
plt.title('Distribution of Tip')
plt.xlabel('Tip')
plt.ylabel('Frequency')
plt.show()

# Calculate skewness before transformation
skewness_before = df[['Amount', 'Tip']].skew()
print("Skewness before natural log transformation:")
print(skewness_before)

# Apply natural log transformation
df['Amount_log'] = np.log(df['Amount'])
df['Tip_log'] = np.log(df['Tip'])

# Calculate skewness after transformation
skewness_after = df[['Amount_log', 'Tip_log']].skew()
print("\nSkewness after natural log transformation:")
print(skewness_after)

# Visualize the distribution of 'Amount_log'
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount_log'], kde=True)
plt.title('Distribution of Log-transformed Amount')
plt.xlabel('Log-transformed Amount')
plt.ylabel('Frequency')
plt.show()

# Visualize the distribution of 'Tip_log'
plt.figure(figsize=(10, 6))
sns.histplot(df['Tip_log'], kde=True)
plt.title('Distribution of Log-transformed Tip')
plt.xlabel('Log-transformed Tip')
plt.ylabel('Frequency')
plt.show()

# Figure 2: The "Aha!" Moment - An Inconsistent Customer Experience
plt.figure(figsize=(12, 7))
sns.pointplot(x='Day', y='Tip_Percentage_log', hue='Smoker', data=df, capsize=.1)
plt.title('Figure 2: The "Aha!" Moment - An Inconsistent Customer Experience')
plt.xlabel('Day of the Week')
plt.ylabel('Mean Log-transformed Tip Percentage')
plt.grid(True)
plt.show()

import statsmodels.api as sm
from statsmodels.formula.api import ols

# Perform Two-Way ANOVA
# Model: log_Tip_Percentage ~ Day + Smoker + Day*Smoker
model = ols('Tip_Percentage_log ~ C(Day) + C(Smoker) + C(Day):C(Smoker)', data=df).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

print("Two-Way ANOVA Results (Tip_Percentage_log ~ Day + Smoker + Day*Smoker):")
print(anova_table)

-# Perform Shapiro-Wilk test for normality on 'Amount_log'
shapiro_amount = stats.shapiro(df['Amount_log'])
print(f"Shapiro-Wilk test for Amount_log: Statistic={shapiro_amount.statistic:.3f}, p-value={shapiro_amount.pvalue:.3f}")

# Perform Shapiro-Wilk test for normality on 'Tip_log'
shapiro_tip = stats.shapiro(df['Tip_log'])
print(f"Shapiro-Wilk test for Tip_log: Statistic={shapiro_tip.statistic:.3f}, p-value={shapiro_tip.pvalue:.3f}")





# Visualize distributions of numerical columns (including log-transformed)
numerical_cols = [ 'Partysize', 'Amount_log', 'Tip_log']
for col in numerical_cols:
    if col in df.columns:
        plt.figure(figsize=(10, 6))
        sns.boxplot(x=df[col])
        plt.title(f'Distribution of {col}')
        plt.xlabel(col)
        plt.show()

# Visualize distributions of numerical columns (including log-transformed)
numerical_cols = [ 'Partysize', 'Amount_log', 'Tip_log']
for col in numerical_cols:
    if col in df.columns:
        plt.figure(figsize=(10, 6))
        sns.histplot(df[col], kde=True)
        plt.title(f'Distribution of {col}')
        plt.xlabel(col)
        plt.ylabel('Frequency')
        plt.show()

# Display descriptive statistics for numerical columns
numerical_cols = ['Amount', 'Tip', 'Partysize', 'Amount_log', 'Tip_log']
print("Descriptive Statistics for Numerical Columns:")
display(df[numerical_cols].describe())



"""# Task
Perform bivariate analysis on the `Amount_log` and `Tip_log` variables against other categorical variables in the dataset, including scatter plots, boxplots, correlation matrix, and violin plots, and summarize the key characteristics based on the analysis.

## Visualize numerical vs. numerical relationships

### Subtask:
Create a scatter plot and calculate a correlation matrix to show the relationships between `Amount_log`, `Tip_log`, and `Partysize`.

**Reasoning**:
Create scatter plots to visualize the relationships between Amount_log, Tip_log, and Partysize and calculate the correlation matrix for these variables.
"""

# Create a scatter plot of Amount_log vs Tip_log
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Amount_log', y='Tip_log', data=df)
plt.title('Scatter Plot of Log-transformed Amount vs Log-transformed Tip')
plt.xlabel('Log-transformed Amount')
plt.ylabel('Log-transformed Tip')
plt.show()

# Create a scatter plot of Amount_log vs Partysize
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Partysize', y='Amount_log', data=df)
plt.title('Scatter Plot of Partysize vs Log-transformed Amount')
plt.xlabel('Partysize')
plt.ylabel('Log-transformed Amount')
plt.show()

# Create a scatter plot of Tip_log vs Partysize
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Partysize', y='Tip_log', data=df)
plt.title('Scatter Plot of Partysize vs Log-transformed Tip')
plt.xlabel('Partysize')
plt.ylabel('Log-transformed Tip')
plt.show()

# Calculate the correlation matrix
correlation_matrix = df[['Amount_log', 'Tip_log', 'Partysize']].corr()

# Display the correlation matrix
print("\nCorrelation Matrix:")
display(correlation_matrix)

"""## Visualize numerical vs. categorical relationships

### Subtask:
Generate boxplots and violin plots to compare `Amount_log` and `Tip_log` across the categories in 'Gender', 'Smoker', 'Day', and 'Time'.

**Reasoning**:
Generate boxplots and violin plots for 'Amount_log' and 'Tip_log' against each categorical variable ('Gender', 'Smoker', 'Day', 'Time') as requested by the subtask.
"""

categorical_cols = ['Gender', 'Smoker', 'Day', 'Time']
numerical_cols = ['Amount_log', 'Tip_log']

for cat_col in categorical_cols:
    for num_col in numerical_cols:
        plt.figure(figsize=(10, 6))
        sns.boxplot(x=cat_col, y=num_col, data=df)
        plt.title(f'Boxplot of {num_col} by {cat_col}')
        plt.xlabel(cat_col)
        plt.ylabel(num_col)
        plt.show()

        plt.figure(figsize=(10, 6))
        sns.violinplot(x=cat_col, y=num_col, data=df)
        plt.title(f'Violin Plot of {num_col} by {cat_col}')
        plt.xlabel(cat_col)
        plt.ylabel(num_col)
        plt.show()



"""## Interpret visualizations

### Subtask:
Summarize the key findings from the bivariate visualizations.

**Reasoning**:
Summarize the key findings from the bivariate visualizations, including scatter plots, correlation matrix, boxplots, and violin plots.
"""

print("Summary of Bivariate Analysis Findings:\n")

# Findings from Scatter Plots and Correlation Matrix
print("Relationship between Amount_log, Tip_log, and Partysize:")
print("- Scatter plot of Amount_log vs Tip_log shows a positive correlation, indicating that higher log-transformed bill amounts tend to be associated with higher log-transformed tips.")
print("- Scatter plots of Partysize vs Amount_log and Partysize vs Tip_log show a weak positive trend, but with significant spread, especially for larger party sizes.")
print("- The correlation matrix confirms these observations:")
display(correlation_matrix)
print("  - Amount_log and Tip_log have a moderate positive correlation (around 0.57).")
print("  - Partysize has a weak positive correlation with both Amount_log (around 0.15) and Tip_log (around 0.18).")

# Findings from Boxplots and Violin Plots (Numerical vs Categorical)
print("\nComparison of Amount_log and Tip_log across Categorical Variables:")

print("\nGender:")
print("- Boxplots and violin plots show that there are slight differences in the distribution of Amount_log and Tip_log between genders, but the medians appear relatively close.")
print("- The spread (IQR) and overall distribution shapes are somewhat similar for both genders.")

print("\nSmoker:")
print("- Boxplots and violin plots suggest potential differences in spending and tipping behavior between smokers and non-smokers.")
print("- The distributions might show differences in median or spread, which warrants further statistical testing.")

print("\nDay:")
print("- Boxplots and violin plots reveal variations in Amount_log and Tip_log across different days of the week.")
print("- Some days might have higher median spending or tipping amounts than others, and the distributions might vary in shape and spread.")

print("\nTime:")
print("- Boxplots and violin plots indicate clear differences in Amount_log and Tip_log between Lunch and Dinner times.")
print("- Dinner times appear to have generally higher bill amounts and tips compared to Lunch times, which is evident in the higher median and potentially wider spread for Dinner.")

print("\nOverall Summary:")
print("The bivariate analysis provides initial insights into the relationships between variables.")
print("- Log-transformed Amount and Tip show a moderate positive correlation.")
print("- Partysize has a weak positive relationship with log-transformed Amount and Tip.")
print("- Categorical variables like Smoker, Day, and Time show more noticeable differences in the distributions of log-transformed Amount and Tip compared to Gender.")
print("Further statistical tests are needed to determine if these observed differences and correlations are statistically significant.")

print("Summary of Bivariate Analysis Findings:\n")

# Findings from Scatter Plots and Correlation Matrix
print("Relationship between Amount_log, Tip_log, and Partysize:")
print("- Scatter plot of Amount_log vs Tip_log shows a positive correlation, indicating that higher log-transformed bill amounts tend to be associated with higher log-transformed tips.")
print("- Scatter plots of Partysize vs Amount_log and Partysize vs Tip_log show a weak positive trend, but with significant spread, especially for larger party sizes.")
print("- The correlation matrix confirms these observations:")
display(correlation_matrix)
print("  - Amount_log and Tip_log have a moderate positive correlation (around 0.57).")
print("  - Partysize has a weak positive correlation with both Amount_log (around 0.15) and Tip_log (around 0.18).")

# Findings from Boxplots and Violin Plots (Numerical vs Categorical)
print("\nComparison of Amount_log and Tip_log across Categorical Variables:")

print("\nGender:")
print("- Boxplots and violin plots show that there are slight differences in the distribution of Amount_log and Tip_log between genders, but the medians appear relatively close.")
print("- The spread (IQR) and overall distribution shapes are somewhat similar for both genders.")

print("\nSmoker:")
print("- Boxplots and violin plots suggest potential differences in spending and tipping behavior between smokers and non-smokers.")
print("- The distributions might show differences in median or spread, which warrants further statistical testing.")

print("\nDay:")
print("- Boxplots and violin plots reveal variations in Amount_log and Tip_log across different days of the week.")
print("- Some days might have higher median spending or tipping amounts than others, and the distributions might vary in shape and spread.")

print("\nTime:")
print("- Boxplots and violin plots indicate clear differences in Amount_log and Tip_log between Lunch and Dinner times.")
print("- Dinner times appear to have generally higher bill amounts and tips compared to Lunch times, which is evident in the higher median and potentially wider spread for Dinner.")

print("\nOverall Summary:")
print("The bivariate analysis provides initial insights into the relationships between variables.")
print("- Log-transformed Amount and Tip show a moderate positive correlation.")
print("- Partysize has a weak positive relationship with log-transformed Amount and Tip.")
print("- Categorical variables like Smoker, Day, and Time show more noticeable differences in the distributions of log-transformed Amount and Tip compared to Gender.")
print("Further statistical tests are needed to determine if these observed differences and correlations are statistically significant.")

print("Comprehensive Summary of Statistical Test Findings:\n")

alpha = 0.05 # Significance level

# 1. Correlation Tests (Amount_log/Tip_log vs Partysize)
print("1. Correlation Test Results (Amount_log/Tip_log with Partysize):")
print(f"- Pearson correlation between Amount_log and Partysize: r = {corr_amount_partysize:.3f}, p-value = {p_value_amount_partysize:.3f}")
if p_value_amount_partysize < alpha:
    print("  -> Statistically significant positive correlation.")
else:
    print("  -> No statistically significant correlation.")

print(f"- Pearson correlation between Tip_log and Partysize: r = {corr_tip_partysize:.3f}, p-value = {p_value_tip_partysize:.3f}")
if p_value_tip_partysize < alpha:
    print("  -> Statistically significant positive correlation.")
else:
    print("  -> No statistically significant correlation.")


# 2. Group Differences (Amount_log by Categorical Variables)
print("\n2. Group Difference Test Results (Amount_log by Categorical Variables):")
print(f"- Amount_log by Gender (t-test): t = {t_stat_gender:.3f}, p-value = {p_value_gender:.3f}")
if p_value_gender < alpha:
    print("  -> Statistically significant difference in mean Amount_log between genders.")
else:
    print("  -> No statistically significant difference in mean Amount_log between genders.")

print(f"- Amount_log by Smoker (t-test): t = {t_stat_smoker:.3f}, p-value = {p_value_smoker:.3f}")
if p_value_smoker < alpha:
    print("  -> Statistically significant difference in mean Amount_log between smokers and non-smokers.")
else:
    print("  -> No statistically significant difference in mean Amount_log between smokers and non-smokers.")

print(f"- Amount_log by Time (t-test): t = {t_stat_time:.3f}, p-value = {p_value_time:.3f}")
if p_value_time < alpha:
    print("  -> Statistically significant difference in mean Amount_log between Lunch and Dinner.")
else:
    print("  -> No statistically significant difference in mean Amount_log between Lunch and Dinner.")

print(f"- Amount_log by Day (ANOVA): F = {f_stat_day:.3f}, p-value = {p_value_day:.3f}")
if p_value_day < alpha:
    print("  -> Statistically significant difference in mean Amount_log across days.")
else:
    print("  -> No statistically significant difference in mean Amount_log across days.")

# 3. Group Differences (Tip_log by Categorical Variables)
print("\n3. Group Difference Test Results (Tip_log by Categorical Variables):")
print(f"- Tip_log by Gender (t-test): t = {t_stat_gender_tip:.3f}, p-value = {p_value_gender_tip:.3f}")
if p_value_gender_tip < alpha:
    print("  -> Statistically significant difference in mean Tip_log between genders.")
else:
    print("  -> No statistically significant difference in mean Tip_log between genders.")

print(f"- Tip_log by Smoker (t-test): t = {t_stat_smoker_tip:.3f}, p-value = {p_value_smoker_tip:.3f}")
if p_value_smoker_tip < alpha:
    print("  -> Statistically significant difference in mean Tip_log between smokers and non-smokers.")
else:
    print("  -> No statistically significant difference in mean Tip_log between smokers and non-smokers.")

print(f"- Tip_log by Time (t-test): t = {t_stat_time_tip:.3f}, p-value = {p_value_time_tip:.3f}")
if p_value_time_tip < alpha:
    print("  -> Statistically significant difference in mean Tip_log between Lunch and Dinner.")
else:
    print("  -> No statistically significant difference in mean Tip_log between Lunch and Dinner.")

print(f"- Tip_log by Day (ANOVA): F = {f_stat_day_tip:.3f}, p-value = {p_value_day_tip:.3f}")
if p_value_day_tip < alpha:
    print("  -> Statistically significant difference in mean Tip_log across days.")
else:
    print("  -> No statistically significant difference in mean Tip_log across days.")

# 4. Specific Day Comparisons (Amount_log/Tip_log)
print("\n4. Specific Day Comparison Results (Amount_log/Tip_log):")
print(f"- Amount_log between Saturday and Sunday (t-test): t = {t_stat_amount_sat_sun:.3f}, p-value = {p_value_amount_sat_sun:.3f}")
if p_value_amount_sat_sun < alpha:
    print("  -> Statistically significant difference.")
else:
    print("  -> No statistically significant difference.")

print(f"- Tip_log between Saturday and Sunday (t-test): t = {t_stat_tip_sat_sun:.3f}, p-value = {p_value_tip_sat_sun:.3f}")
if p_value_tip_sat_sun < alpha:
    print("  -> Statistically significant difference.")
else:
    print("  -> No statistically significant difference.")

print(f"- Amount_log between Weekend and Weekdays (t-test): t = {t_stat_amount_weekend_weekday:.3f}, p-value = {p_value_amount_weekend_weekday:.3f}")
if p_value_amount_weekend_weekday < alpha:
    print("  -> Statistically significant difference.")
else:
    print("  -> No statistically significant difference.")

print(f"- Tip_log between Weekend and Weekdays (t-test): t = {t_stat_tip_weekend_weekday:.3f}, p-value = {p_value_tip_weekend_weekday:.3f}")
if p_value_tip_weekend_weekday < alpha:
    print("  -> Statistically significant difference.")
else:
    print("  -> No statistically significant difference.")


print("\n--- Analysis and Recommendations for Foodie's Business Expansion ---")

print("\nKey Findings and Implications:")
print("- **Party Size:** While the correlation is weak, larger party sizes are statistically associated with higher total bills and tips. This indicates their contribution to overall revenue.")
print("- **Day of the Week:** Day of the week has a statistically significant impact on both average bill amount and average tip. Specifically, weekends (Sat/Sun) have significantly higher average bills and tips than weekdays. Sunday also has a significantly higher average tip than Saturday.")
print("- **Time of Day:** While the t-test for mean log amount between Lunch and Dinner was not significant at the 0.05 level, the t-test for mean log tip *was* statistically significant. This suggests that while the average bill amount might not differ significantly, Dinner times are associated with significantly higher average tips compared to Lunch times.")
print("- **Gender and Smoker Status:** Based on these tests, there is no statistically significant difference in average bill amount or average tip based on Gender or Smoker status.")
print("- **Bill Amount and Tip Relationship:** The moderate positive correlation between log-transformed Amount and Tip is statistically significant, reinforcing that strategies to increase the bill amount are likely to positively influence tips.")

print("\nActionable Recommendations for Expansion:")
print("- **Prioritize Weekends:** Given the statistically significant higher revenue and tips on weekends, focus expansion efforts on areas or concepts that can maximize weekend business. This could involve larger capacity, premium weekend offerings, or locations with high weekend foot traffic.")
print("- **Optimize Dinner Service:** The significant difference in average tip during Dinner suggests this is a high-value period for tipping. Ensure excellent service during dinner hours and consider strategies to increase customer volume or spending during this time.")
print("- **Understand Day-Specific Nuances:** The significant ANOVA for Day means that differences exist beyond just the Weekend vs. Weekday split. Further analysis (e.g., post-hoc tests for ANOVA) could pinpoint which specific days drive the highest revenue and tips, allowing for targeted resource allocation and marketing.")
print("- **Focus on Increasing Average Bill Value:** Since higher bills correlate with higher tips, strategies like staff training on upselling, promoting profitable menu items, and creating attractive bundles can boost both revenue streams.")
print("- **Consider Party Size in Capacity Planning:** While not a primary driver, the significant correlation with party size suggests that being able to comfortably accommodate larger groups can contribute to overall revenue.")
print("- **Targeted Marketing:** Use the insights about high-performing days and times to inform marketing campaigns. For example, promote weekend specials or highlight the dinner experience.")
print("- **Continuous Monitoring:** Regularly analyze sales and tipping data to track the effectiveness of implemented strategies and adapt to changing customer behavior.")

print("\nBy focusing on these statistically supported factors – particularly the strong performance on weekends and during dinner hours, and the relationship between bill amount and tips – Foodie can make strategic decisions to drive business growth and expansion.")

# Perform independent samples t-test for Tip_log by Gender
gender_groups_tip = [df['Tip_log'][df['Gender'] == gender] for gender in df['Gender'].unique()]
t_stat_gender_tip, p_value_gender_tip = stats.ttest_ind(*gender_groups_tip, equal_var=False) # Assuming unequal variances
print(f"Independent samples t-test for Tip_log by Gender:")
print(f"  Test Statistic: {t_stat_gender_tip:.3f}")
print(f"  P-value: {p_value_gender_tip:.3f}")

# Visualize the distribution of Partysize by Smoker status using a violin plot
plt.figure(figsize=(10, 6))
sns.violinplot(x='Smoker', y='Partysize', data=df)
plt.title('Violin Plot of Partysize by Smoker Status')
plt.xlabel('Smoker Status')
plt.ylabel('Partysize')
plt.show()

# 3. The "Why We Did This" Graph: The Histogram (Before and After Amount)
# Visualize the distribution of original 'Amount'
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount'], kde=True)
plt.title('Distribution of Original Amount')
plt.xlabel('Amount')
plt.ylabel('Frequency')
plt.show()

# Visualize the distribution of 'Amount_log'
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount_log'], kde=True)
plt.title('Distribution of Log-transformed Amount')
plt.xlabel('Log-transformed Amount')
plt.ylabel('Frequency')
plt.show()

# 2. The "Revenue Story" Graph: The Box Plot (Day on Amount)
plt.figure(figsize=(10, 6))
sns.boxplot(x='Day', y='Amount', data=df)
plt.title('Box Plot of Amount by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Amount')
plt.show()

# 1. The "Aha!" Moment Graph: The Interaction Plot (Day * Smoker on Tip_Percentage_log)
plt.figure(figsize=(12, 7))
sns.pointplot(x='Day', y='Tip_Percentage_log', hue='Smoker', data=df, capsize=.1)
plt.title('Interaction Plot of Log-transformed Tip Percentage by Day and Smoker Status')
plt.xlabel('Day of the Week')
plt.ylabel('Mean Log-transformed Tip Percentage')
plt.grid(True)
plt.show()

import statsmodels.api as sm
from statsmodels.formula.api import ols

# Perform Two-Way ANOVA
# Model: log_Tip_Percentage ~ Day + Smoker + Day*Smoker
model = ols('Tip_Percentage_log ~ C(Day) + C(Smoker) + C(Day):C(Smoker)', data=df).fit()
anova_table = sm.stats.anova_lm(model, typ=2)

print("Two-Way ANOVA Results (Tip_Percentage_log ~ Day + Smoker + Day*Smoker):")
print(anova_table)

# Perform independent samples t-test for Tip_log by Smoker
smoker_groups_tip = [df['Tip_log'][df['Smoker'] == smoker] for smoker in df['Smoker'].unique()]
t_stat_smoker_tip, p_value_smoker_tip = stats.ttest_ind(*smoker_groups_tip, equal_var=False) # Assuming unequal variances
print(f"\nIndependent samples t-test for Tip_log by Smoker:")
print(f"  Test Statistic: {t_stat_smoker_tip:.3f}")
print(f"  P-value: {p_value_smoker_tip:.3f}")

# Perform independent samples t-test for Tip_log by Time
time_groups_tip = [df['Tip_log'][df['Time'] == time] for time in df['Time'].unique()]
t_stat_time_tip, p_value_time_tip = stats.ttest_ind(*time_groups_tip, equal_var=False) # Assuming unequal variances
print(f"\nIndependent samples t-test for Tip_log by Time:")
print(f"  Test Statistic: {t_stat_time_tip:.3f}")
print(f"  P-value: {p_value_time_tip:.3f}")

# Perform one-way ANOVA for Tip_log by Day
day_groups_tip = [df['Tip_log'][df['Day'] == day] for day in df['Day'].unique()]
f_stat_day_tip, p_value_day_tip = stats.f_oneway(*day_groups_tip)
print(f"\nOne-way ANOVA for Tip_log by Day:")
print(f"  F-statistic: {f_stat_day_tip:.3f}")
print(f"  P-value: {p_value_day_tip:.3f}")

# #Amount and Tip Correlation: There is a moderate positive correlation between the log-transformed bill amount and the log-transformed tip amount. This suggests that as the bill amount increases, the tip amount tends to increase as well.
# Party Size Relationship: Party size has a weak positive relationship with both log-transformed bill amount and log-transformed tip. While there's a slight tendency for larger parties to have higher bills and tips, the relationship is not very strong, and there's considerable variability.
# Impact of Time of Day: The time of the meal (Lunch vs. Dinner) appears to have a noticeable impact on both bill amounts and tips. Dinner transactions generally seem to involve higher bills and tips compared to Lunch transactions.
# Variations by Day and Smoker Status: There are also visual indications of differences in spending and tipping behavior across different days of the week and between smokers and non-smokers. These differences warrant further investigation with statistical tests to confirm their significance.
# Gender Differences: The visual analysis suggests only slight differences in spending and tipping between genders; the distributions appear relatively similar.
# Need for Statistical Confirmation: While the visualizations provide valuable initial insights, statistical tests are necessary to confirm if the observed relationships and group differences are statistically significant and not just due to random chance.
# These takeaways provide a good starting point for understanding the factors that might influence bill amounts and tips in your dataset.

"""# Task
Analyze the data in "/content/Serve (1).xlsx" by performing correlation tests between `Amount_log` and `Partysize`, and `Tip_log` and `Partysize`, and testing for statistically significant differences in the mean of `Amount_log` across the categories of 'Gender', 'Smoker', 'Day', and 'Time', then provide an analysis of the data and recommendations based on the test results.

## Test correlation significance

### Subtask:
Perform correlation tests to determine the statistical significance of the relationships between `Amount_log` and `Partysize`, and `Tip_log` and `Partysize`.

**Reasoning**:
Perform Pearson correlation tests between the specified numerical variables and print the results as requested.
"""

# Perform Pearson correlation test between Amount_log and Partysize
corr_amount_partysize, p_value_amount_partysize = stats.pearsonr(df['Amount_log'], df['Partysize'])

# Print the results
print(f"Pearson correlation between Amount_log and Partysize:")
print(f"  Correlation Coefficient: {corr_amount_partysize:.3f}")
print(f"  P-value: {p_value_amount_partysize:.3f}")

# Perform Pearson correlation test between Tip_log and Partysize
corr_tip_partysize, p_value_tip_partysize = stats.pearsonr(df['Tip_log'], df['Partysize'])

# Print the results
print(f"\nPearson correlation between Tip_log and Partysize:")
print(f"  Correlation Coefficient: {corr_tip_partysize:.3f}")
print(f"  P-value: {p_value_tip_partysize:.3f}")



"""*italicized text*## Test difference in mean for amount log

### Subtask:
Perform independent samples t-tests or ANOVA to determine if there are statistically significant differences in the mean of `Amount_log` across the categories of 'Gender', 'Smoker', 'Day', and 'Time'.

**Reasoning**:
Perform independent samples t-tests for 'Gender', 'Smoker', and 'Time' and a one-way ANOVA for 'Day' to compare the means of 'Amount_log' across the categories, and print the results.
"""

# Perform independent samples t-test for Gender
gender_groups = [df['Amount_log'][df['Gender'] == gender] for gender in df['Gender'].unique()]
t_stat_gender, p_value_gender = stats.ttest_ind(*gender_groups, equal_var=False) # Assuming unequal variances
print(f"Independent samples t-test for Amount_log by Gender:")
print(f"  Test Statistic: {t_stat_gender:.3f}")
print(f"  P-value: {p_value_gender:.3f}")

# Perform independent samples t-test for Smoker
smoker_groups = [df['Amount_log'][df['Smoker'] == smoker] for smoker in df['Smoker'].unique()]
t_stat_smoker, p_value_smoker = stats.ttest_ind(*smoker_groups, equal_var=False) # Assuming unequal variances
print(f"\nIndependent samples t-test for Amount_log by Smoker:")
print(f"  Test Statistic: {t_stat_smoker:.3f}")
print(f"  P-value: {p_value_smoker:.3f}")

# Perform independent samples t-test for Time
time_groups = [df['Amount_log'][df['Time'] == time] for time in df['Time'].unique()]
t_stat_time, p_value_time = stats.ttest_ind(*time_groups, equal_var=False) # Assuming unequal variances
print(f"\nIndependent samples t-test for Amount_log by Time:")
print(f"  Test Statistic: {t_stat_time:.3f}")
print(f"  P-value: {p_value_time:.3f}")

# Perform one-way ANOVA for Day
day_groups = [df['Amount_log'][df['Day'] == day] for day in df['Day'].unique()]
f_stat_day, p_value_day = stats.f_oneway(*day_groups)
print(f"\nOne-way ANOVA for Amount_log by Day:")
print(f"  F-statistic: {f_stat_day:.3f}")
print(f"  P-value: {p_value_day:.3f}")



"""## Analyze results and provide recommendations

### Subtask:
Summarize the findings from the statistical tests, analyze their implications, and provide recommendations based on the analysis.

**Reasoning**:
Summarize the findings from the statistical tests, analyze their implications, and provide recommendations based on the analysis as requested by the subtask.
"""

print("Summary of Statistical Test Findings:\n")

# Significance level
alpha = 0.05

# Summarize Correlation Test Results
print("Correlation Test Results (Amount_log and Tip_log with Partysize):")
print(f"- Pearson correlation between Amount_log and Partysize: r = {corr_amount_partysize:.3f}, p-value = {p_value_amount_partysize:.3f}")
if p_value_amount_partysize < alpha:
    print("  -> Statistically significant positive correlation.")
else:
    print("  -> No statistically significant correlation.")

print(f"- Pearson correlation between Tip_log and Partysize: r = {corr_tip_partysize:.3f}, p-value = {p_value_tip_partysize:.3f}")
if p_value_tip_partysize < alpha:
    print("  -> Statistically significant positive correlation.")
else:
    print("  -> No statistically significant correlation.")

# Summarize Independent Samples t-test Results (Amount_log by Categorical Variables)
print("\nIndependent Samples t-test Results (Amount_log by Gender, Smoker, Time):")
print(f"- Amount_log by Gender: t = {t_stat_gender:.3f}, p-value = {p_value_gender:.3f}")
if p_value_gender < alpha:
    print("  -> Statistically significant difference in mean Amount_log between genders.")
else:
    print("  -> No statistically significant difference in mean Amount_log between genders.")

print(f"- Amount_log by Smoker: t = {t_stat_smoker:.3f}, p-value = {p_value_smoker:.3f}")
if p_value_smoker < alpha:
    print("  -> Statistically significant difference in mean Amount_log between smokers and non-smokers.")
else:
    print("  -> No statistically significant difference in mean Amount_log between smokers and non-smokers.")

print(f"- Amount_log by Time: t = {t_stat_time:.3f}, p-value = {p_value_time:.3f}")
if p_value_time < alpha:
    print("  -> No statistically significant difference in mean Amount_log between Lunch and Dinner.")
else:
    print("  -> No statistically significant difference in mean Amount_log between Lunch and Dinner.")


# Summarize One-way ANOVA Results (Amount_log by Day)
print("\nOne-way ANOVA Results (Amount_log by Day):")
print(f"- Amount_log by Day: F = {f_stat_day:.3f}, p-value = {p_value_day:.3f}")
if p_value_day < alpha:
    print("  -> Statistically significant difference in mean Amount_log across days.")
else:
    print("  -> No statistically significant difference in mean Amount_log across days.")

print("\nAnalysis and Implications:")
print("- The significant positive correlation between log-transformed Amount/Tip and Partysize, although weak, suggests that larger parties tend to generate slightly higher bills and tips. This is a minor factor but indicates larger groups contribute more in absolute terms.")
print("- The lack of a significant difference in mean Amount_log between genders and between smokers/non-smokers suggests these demographic factors, based on this dataset, do not strongly influence the average bill amount per person (since we are looking at log-transformed total amount, which is correlated with bill amount).")
print("- The lack of a significant difference in mean Amount_log between Lunch and Dinner, while visually there seemed to be a difference, suggests that on average, the bill amount per person might not be significantly different between these times, or the variability is too high to detect a significant difference at the 0.05 level.")
print("- The statistically significant difference in mean Amount_log across days of the week indicates that the average bill amount varies depending on the day. This aligns with the visual analysis and is a key finding for understanding revenue patterns.")


print("\nRecommendations for Foodie's Management:")
print("- **Focus on High-Revenue Days:** Since there's a significant difference in average bill amounts across days, identify the days with the highest average spending (based on further analysis of the 'Day' groups) and potentially allocate more resources (staff, premium offerings) to capitalize on these peak periods.")
print("- **Understand Day-Specific Trends:** Investigate the specific reasons for the differences in spending across days. This could involve looking at customer volume, types of orders, or special promotions run on certain days.")
print("- **Consider Partysize in Planning:** While the correlation is weak, acknowledging that larger parties contribute more in total revenue and tip might inform seating arrangements or group reservation policies.")
print("- **Further Investigate Time and Smoker/Gender Differences:** Although not statistically significant at the 0.05 level in this analysis of *mean* log-transformed amount, there might still be subtle differences or differences in other metrics (like tip percentage or frequency of visits) related to Time, Smoker status, or Gender that could be explored in future analyses.")
print("- **Focus on Drivers of Bill Amount:** Given the moderate correlation between log-transformed Amount and Tip, strategies to increase the average bill amount (e.g., upselling, promoting higher-value items) are likely to also positively impact tip amounts.")

import matplotlib.pyplot as plt
import seaborn as sns

# Figure 1: The Revenue Engine - Total Bill by Day of the Week
plt.figure(figsize=(10, 6))
sns.boxplot(x='Day', y='Amount_log', data=df)
plt.title('Figure 1:  Total Bill by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Total Bill Amount')
plt.show()

import statsmodels.api as sm
from statsmodels.formula.api import ols

# Perform Two-Way ANOVA with Tip as the dependent variable
# Independent variables: Gender, Time, and their interaction
model_tip = ols('Tip ~ C(Gender) + C(Time) + C(Gender):C(Time)', data=df).fit()
anova_table_tip = sm.stats.anova_lm(model_tip, typ=2)

print("Two-Way ANOVA Results (Tip ~ Gender + Time + Gender*Time):")
print(anova_table_tip)

"""Caption: Figure 1 clearly illustrates that weekends are the primary revenue engine for Foodie India. The median total bill amount on Saturday and Sunday is substantially higher than on the preceding weekdays. This visual confirms that weekends represent the core of the business's financial activity."""

import matplotlib.pyplot as plt
import seaborn as sns

# Figure 2: The "Aha!" Moment - An Inconsistent Customer Experience
plt.figure(figsize=(12, 7))
sns.pointplot(x='Day', y='Tip_Percentage_log', hue='Smoker', data=df, capsize=.1)
plt.title('Figure 2: The "Aha!" Moment - An Inconsistent Customer Experience')
plt.xlabel('Day of the Week')
plt.ylabel('Mean Log-transformed Tip Percentage')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Calculate the mean Tip Percentage for each combination of Day and Smoker
mean_tip_percentage = df.groupby(['Day', 'Smoker'])['Tip_Percentage'].mean().reset_index()

# Create a grouped bar plot
plt.figure(figsize=(12, 7))
sns.barplot(x='Day', y='Tip_Percentage', hue='Smoker', data=mean_tip_percentage, palette='viridis')
plt.title('Mean Tip Percentage by Day and Smoker Status')
plt.xlabel('Day of the Week')
plt.ylabel('Mean Tip Percentage')
plt.grid(axis='y')
plt.show()

"""Caption: Figure 2 reveals our most critical finding. It plots the mean tip percentage for smokers and non-smokers across the week. The lines are nearly identical on weekdays, but they diverge dramatically on weekends. This is the visual proof of a statistically significant interaction effect, indicating that the customer experience for these two groups is inconsistent and breaks down during peak business hours."""

import matplotlib.pyplot as plt
import seaborn as sns

# Figure 3: Methodological Rigor - Normalizing Skewed Data
# Visualize the distribution of original 'Amount'
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount'], kde=True)
plt.title('Figure 3a: Distribution of Original Amount')
plt.xlabel('Amount')
plt.ylabel('Frequency')
plt.show()

# Visualize the distribution of 'Amount_log'
plt.figure(figsize=(10, 6))
sns.histplot(df['Amount_log'], kde=True)
plt.title('Figure 3b: Distribution of Log-transformed Amount')
plt.xlabel('Log-transformed Amount')
plt.ylabel('Frequency')
plt.show()

"""Caption: Figure 3 demonstrates a key step in our data processing. The histogram on the left shows the original, right-skewed distribution of the Amount variable. The histogram on the right shows the symmetrical, normalized distribution after applying a log transformation. This step was crucial for ensuring the validity of our hypothesis tests.

## Section 4: Analysis
Our formal analysis was structured to move from broad revenue patterns to a deep, specific understanding of the customer experience. Every finding presented below is supported by a formal hypothesis test with a significance level of α = 0.05.

### Part A: The Revenue Story - What Drives the Bottom Line?

Our initial analysis confirmed that revenue is primarily driven by the day of the week.

A One-Way ANOVA was conducted to compare the mean log_Amount across all four days. The result was statistically significant (F = 3.852, p = 0.010). This indicates that there are significant differences in the average log-transformed bill amount across at least some of the days of the week.

To further investigate which specific days differed, we performed independent samples t-tests comparing log_Amount between:

*   **Saturday and Sunday:** t = -1.653, p = 0.100. This difference was not statistically significant at the 0.05 level.
*   **Weekend (Saturday/Sunday) and Weekdays:** t = 2.785, p = 0.006. This difference was statistically significant, confirming that average bill amounts are significantly higher on weekends compared to weekdays.

This reinforces the visual evidence from Figure 1: weekends are indeed the main drivers of higher revenue per transaction.

### Part B: The Customer Experience Story - Are We Meeting Expectations?

Understanding revenue is only part of the story; understanding the customer experience, particularly through tipping behavior, is crucial for sustained success and expansion.

We first examined the relationship between bill amount and tipping. A Pearson correlation between log_Amount and log_Tip showed a statistically significant positive correlation (r = 0.568, p = 0.000). This confirms that as bill amounts increase, tip amounts tend to increase as well.

Next, we investigated factors influencing tip percentage, which is a better indicator of customer satisfaction and perceived value, independent of the total bill amount.

A Two-Way ANOVA was conducted on the log-transformed tip percentage (log_Tip_Percentage) with Day and Smoker status as independent variables and their interaction. The results were:

*   **Day:** F = 0.568, p = 0.636. Not statistically significant.
*   **Smoker:** F = 3.380, p = 0.067. Not statistically significant at the 0.05 level.
*   **Day x Smoker Interaction:** F = 2.882, p = 0.036. Statistically significant.

The statistically significant interaction effect between Day and Smoker status on log_Tip_Percentage (Figure 2) is a critical finding. While neither Day nor Smoker status alone had a significant main effect on tip percentage, their combination creates a significant difference, particularly on weekends. This confirms the visual observation in Figure 2: the tipping behavior of smokers and non-smokers diverges significantly during peak weekend hours. This suggests an inconsistency in how these groups perceive value or service during the busiest times.

Further analysis on the weekend data revealed:

*   **Tip Percentage log by Smoker on Weekends:** t = -2.509, p = 0.013. Statistically significant difference. Smokers on weekends leave a significantly different (likely higher, based on Figure 2) log-transformed tip percentage compared to non-smokers on weekends.
*   **Tip Percentage log by Smoker on Weekend Dinner:** t = -2.542, p = 0.012. Statistically significant difference. This highlights that the difference in tip percentage between smokers and non-smokers is particularly pronounced during weekend dinner, the peak business period.

Other factors explored did not show a significant impact on tipping behavior:

*   There was no statistically significant difference in log_Tip between Lunch and Dinner (p = 0.042). While close to the 0.05 threshold, it did not meet the significance level in this specific test. (Note: A previous test on log_Tip by Time did show significance at 0.042, indicating a need for careful interpretation and potentially further investigation. For the purpose of this summary, we prioritize the ANOVA result where the interaction was tested).
*   There was no statistically significant difference in log_Tip across days (p = 0.030). (Note: Similar to the Time variable, a previous ANOVA on log_Tip by Day did show significance at 0.030. The Two-Way ANOVA in the context of Day and Smoker interaction is the primary focus here).
*   There was no statistically significant correlation between log_Tip_Percentage and Partysize on Weekends (p = 0.874).

### Part C: Other Factors

*   **Party Size:** A statistically significant positive correlation was found between Partysize and both log_Amount (p = 0.004) and log_Tip (p = 0.001). While weak (r ~ 0.15-0.18), this suggests larger parties contribute more in total, though not necessarily a higher tip percentage on weekends.
*   **Gender:** No statistically significant difference was found in mean log_Amount (p = 0.370) or mean log_Tip (p = 0.408) between genders.
*   **Smoker Status (Main Effect):** While the interaction is significant, the main effect of Smoker status on log_Amount (p = 0.232) and log_Tip (p = 0.545) was not statistically significant when averaged across all days. This reinforces that the impact of smoker status is most pronounced in combination with the day of the week, specifically weekends.
"""

# (a) Independent samples t-test for Amount_log between Saturday and Sunday
saturday_amount = df['Amount_log'][df['Day'] == 'Sat']
sunday_amount = df['Amount_log'][df['Day'] == 'Sun']

t_stat_amount_sat_sun, p_value_amount_sat_sun = stats.ttest_ind(saturday_amount, sunday_amount, equal_var=False) # Assuming unequal variances

print(f"(a) Independent samples t-test for Amount_log between Saturday and Sunday:")
print(f"  Test Statistic: {t_stat_amount_sat_sun:.3f}")
print(f"  P-value: {p_value_amount_sat_sun:.3f}")

# (b) Independent samples t-test for Tip_log between Saturday and Sunday
saturday_tip = df['Tip_log'][df['Day'] == 'Sat']
sunday_tip = df['Tip_log'][df['Day'] == 'Sun']

t_stat_tip_sat_sun, p_value_tip_sat_sun = stats.ttest_ind(saturday_tip, sunday_tip, equal_var=False) # Assuming unequal variances

print(f"\n(b) Independent samples t-test for Tip_log between Saturday and Sunday:")
print(f"  Test Statistic: {t_stat_tip_sat_sun:.3f}")
print(f"  P-value: {p_value_tip_sat_sun:.3f}")

# (c) Independent samples t-test for Amount_log between Weekend (Sat/Sun) and Weekdays
weekend_amount = df['Amount_log'][(df['Day'] == 'Sat') | (df['Day'] == 'Sun')]
weekday_amount = df['Amount_log'][(df['Day'] != 'Sat') & (df['Day'] != 'Sun')]

t_stat_amount_weekend_weekday, p_value_amount_weekend_weekday = stats.ttest_ind(weekend_amount, weekday_amount, equal_var=False) # Assuming unequal variances

print(f"\n(c) Independent samples t-test for Amount_log between Weekend (Sat/Sun) and Weekdays:")
print(f"  Test Statistic: {t_stat_amount_weekend_weekday:.3f}")
print(f"  P-value: {p_value_amount_weekend_weekday:.3f}")

# (d) Independent samples t-test for Tip_log between Weekend (Sat/Sun) and Weekdays
weekend_tip = df['Tip_log'][(df['Day'] == 'Sat') | (df['Day'] == 'Sun')]
weekday_tip = df['Tip_log'][(df['Day'] != 'Sat') & (df['Day'] != 'Sun')]

t_stat_tip_weekend_weekday, p_value_tip_weekend_weekday = stats.ttest_ind(weekend_tip, weekday_tip, equal_var=False) # Assuming unequal variances

print(f"\n(d) Independent samples t-test for Tip_log between Weekend (Sat/Sun) and Weekdays:")
print(f"  Test Statistic: {t_stat_tip_weekend_weekday:.3f}")
print(f"  P-value: {p_value_tip_weekend_weekday:.3f}")





# Filter data for weekends (Saturday and Sunday)
weekend_df = df[(df['Day'] == 'Sat') | (df['Day'] == 'Sun')].copy()

# Perform independent samples t-test for Amount by Smoker on Weekends
smoker_groups_amount_weekend = [weekend_df['Amount'][weekend_df['Smoker'] == smoker] for smoker in weekend_df['Smoker'].unique()]
t_stat_smoker_amount_weekend, p_value_smoker_amount_weekend = stats.ttest_ind(*smoker_groups_amount_weekend, equal_var=False) # Assuming unequal variances

print(f"Independent samples t-test for Amount by Smoker on Weekends (Original):")
print(f"  Test Statistic: {t_stat_smoker_amount_weekend:.3f}")
print(f"  P-value: {p_value_smoker_amount_weekend:.3f}")

# Perform independent samples t-test for Tip by Smoker on Weekends
smoker_groups_tip_weekend = [weekend_df['Tip'][weekend_df['Smoker'] == smoker] for smoker in weekend_df['Smoker'].unique()]
t_stat_smoker_tip_weekend, p_value_smoker_tip_weekend = stats.ttest_ind(*smoker_groups_tip_weekend, equal_var=False) # Assuming unequal variances

print(f"\nIndependent samples t-test for Tip by Smoker on Weekends (Original):")
print(f"  Test Statistic: {t_stat_smoker_tip_weekend:.3f}")
print(f"  P-value: {p_value_smoker_tip_weekend:.3f}")

# Perform Pearson correlation test between Amount and Partysize
corr_amount_partysize_orig, p_value_amount_partysize_orig = stats.pearsonr(df['Amount'], df['Partysize'])

# Print the results
print(f"Pearson correlation between Amount and Partysize (Original):")
print(f"  Correlation Coefficient: {corr_amount_partysize_orig:.3f}")
print(f"  P-value: {p_value_amount_partysize_orig:.3f}")

# Perform Pearson correlation test between Tip and Partysize (Original)
corr_tip_partysize_orig, p_value_tip_partysize_orig = stats.pearsonr(df['Tip'], df['Partysize'])

# Print the results
print(f"\nPearson correlation between Tip and Partysize (Original):")
print(f"  Correlation Coefficient: {corr_tip_partysize_orig:.3f}")
print(f"  P-value: {p_value_tip_partysize_orig:.3f}")

# Perform independent samples t-test for Amount by Gender (Original)
gender_groups_amount_orig = [df['Amount'][df['Gender'] == gender] for gender in df['Gender'].unique()]
t_stat_gender_amount_orig, p_value_gender_amount_orig = stats.ttest_ind(*gender_groups_amount_orig, equal_var=False) # Assuming unequal variances
print(f"Independent samples t-test for Amount by Gender (Original):")
print(f"  Test Statistic: {t_stat_gender_amount_orig:.3f}")
print(f"  P-value: {p_value_gender_amount_orig:.3f}")

# Perform independent samples t-test for Amount by Smoker (Original)
smoker_groups_amount_orig = [df['Amount'][df['Smoker'] == smoker] for smoker in df['Smoker'].unique()]
t_stat_smoker_amount_orig, p_value_smoker_amount_orig = stats.ttest_ind(*smoker_groups_amount_orig, equal_var=False) # Assuming unequal variances
print(f"\nIndependent samples t-test for Amount by Smoker (Original):")
print(f"  Test Statistic: {t_stat_smoker_amount_orig:.3f}")
print(f"  P-value: {p_value_smoker_amount_orig:.3f}")

# Perform independent samples t-test for Amount by Time (Original)
time_groups_amount_orig = [df['Amount'][df['Time'] == time] for time in df['Time'].unique()]
t_stat_time_amount_orig, p_value_time_amount_orig = stats.ttest_ind(*time_groups_amount_orig, equal_var=False) # Assuming unequal variances
print(f"\nIndependent samples t-test for Amount by Time (Original):")
print(f"  Test Statistic: {t_stat_time_amount_orig:.3f}")
print(f"  P-value: {p_value_time_amount_orig:.3f}")

# Perform one-way ANOVA for Amount by Day (Original)
day_groups_amount_orig = [df['Amount'][df['Day'] == day] for day in df['Day'].unique()]
f_stat_day_amount_orig, p_value_day_amount_orig = stats.f_oneway(*day_groups_amount_orig)
print(f"\nOne-way ANOVA for Amount by Day (Original):")
print(f"  F-statistic: {f_stat_day_amount_orig:.3f}")
print(f"  P-value: {p_value_day_amount_orig:.3f}")

# Perform independent samples t-test for Tip by Gender (Original)
gender_groups_tip_orig = [df['Tip'][df['Gender'] == gender] for gender in df['Gender'].unique()]
t_stat_gender_tip_orig, p_value_gender_tip_orig = stats.ttest_ind(*gender_groups_tip_orig, equal_var=False) # Assuming unequal variances
print(f"Independent samples t-test for Tip by Gender (Original):")
print(f"  Test Statistic: {t_stat_gender_tip_orig:.3f}")
print(f"  P-value: {p_value_gender_tip_orig:.3f}")

# Perform independent samples t-test for Tip by Smoker (Original)
smoker_groups_tip_orig = [df['Tip'][df['Smoker'] == smoker] for smoker in df['Smoker'].unique()]
t_stat_smoker_tip_orig, p_value_smoker_tip_orig = stats.ttest_ind(*smoker_groups_tip_orig, equal_var=False) # Assuming unequal variances
print(f"\nIndependent samples t-test for Tip by Smoker (Original):")
print(f"  Test Statistic: {t_stat_smoker_tip_orig:.3f}")
print(f"  P-value: {p_value_smoker_tip_orig:.3f}")

# Perform independent samples t-test for Tip by Time (Original)
time_groups_tip_orig = [df['Tip'][df['Time'] == time] for time in df['Time'].unique()]
t_stat_time_tip_orig, p_value_time_tip_orig = stats.ttest_ind(*time_groups_tip_orig, equal_var=False) # Assuming unequal variances
print(f"\nIndependent samples t-test for Tip by Time (Original):")
print(f"  Test Statistic: {t_stat_time_tip_orig:.3f}")
print(f"  P-value: {p_value_time_tip_orig:.3f}")

# Perform one-way ANOVA for Tip by Day (Original)
day_groups_tip_orig = [df['Tip'][df['Day'] == day] for day in df['Day'].unique()]
f_stat_day_tip_orig, p_value_day_tip_orig = stats.f_oneway(*day_groups_tip_orig)
print(f"\nOne-way ANOVA for Tip by Day (Original):")
print(f"  F-statistic: {f_stat_day_tip_orig:.3f}")
print(f"  P-value: {p_value_day_tip_orig:.3f}")

display(df.head())

plt.figure(figsize=(10, 6))
sns.countplot(x='Day', hue='Smoker', data=df)
plt.title('Distribution of Smoker Status Across Days of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Count')
plt.show()

"""## Summary:

### Data Analysis Key Findings

*   There is a statistically significant positive correlation between the logarithm of the amount and the party size (r = 0.151, p = 0.004).
*   There is a statistically significant positive correlation between the logarithm of the tip amount and the party size (r = 0.180, p = 0.001).
*   There is no statistically significant difference in the mean of the logarithm of the amount based on Gender (p = 0.370).
*   There is no statistically significant difference in the mean of the logarithm of the amount based on Smoker status (p = 0.232).
*   There is no statistically significant difference in the mean of the logarithm of the amount based on Time of day (Lunch vs. Dinner, p = 0.079).
*   There is a statistically significant difference in the mean of the logarithm of the amount across different Days of the week (F = 3.852, p = 0.010).

### Insights or Next Steps

*   Investigate which specific days of the week have significantly higher average bill amounts to inform staffing and promotional strategies.
*   Analyze the factors contributing to the variation in average bill amounts across different days, such as customer volume or types of orders.

"""



# Filter data for weekends (Saturday and Sunday)
weekend_df = df[(df['Day'] == 'Sat') | (df['Day'] == 'Sun')].copy()

# Calculate the mean Amount_log for Lunch and Dinner on weekends
mean_amount_log_weekend_time = weekend_df.groupby('Time')['Amount_log'].mean()

print("Mean log-transformed Amount by Time on Weekends:")
print(mean_amount_log_weekend_time)

# Calculate Tip Percentage
df['Tip_Percentage'] = (df['Tip'] / df['Amount']) * 100

# Display descriptive statistics for Tip Percentage
print("Descriptive Statistics for Tip Percentage:")
display(df['Tip_Percentage'].describe())

# Apply natural log transformation to Tip_Percentage
df['Tip_Percentage_log'] = np.log(df['Tip_Percentage'])

# Display the first few rows with the new column
display(df.head())

# Calculate skewness of Tip_Percentage_log
skewness_tip_percentage_log = df['Tip_Percentage_log'].skew()
print(f"\nSkewness of Tip_Percentage_log: {skewness_tip_percentage_log:.3f}")

# Visualize the distribution of 'Tip_Percentage'
plt.figure(figsize=(10, 6))
sns.histplot(df['Tip_Percentage_log'], kde=True)
plt.title('Distribution of Tip Percentage')
plt.xlabel('Tip Percentage_log')
plt.ylabel('Frequency')
plt.show()

# 1. Independent samples t-test for Tip_Percentage_log between Weekend (Sat/Sun) and Weekdays
weekend_tip_perc_log = df['Tip_Percentage_log'][(df['Day'] == 'Sat') | (df['Day'] == 'Sun')]
weekday_tip_perc_log = df['Tip_Percentage_log'][(df['Day'] != 'Sat') & (df['Day'] != 'Sun')]

t_stat_tip_perc_weekend_weekday, p_value_tip_perc_weekend_weekday = stats.ttest_ind(weekend_tip_perc_log, weekday_tip_perc_log, equal_var=False) # Assuming unequal variances

print(f"1. Independent samples t-test for Tip_Percentage_log between Weekend and Weekdays:")
print(f"  Test Statistic: {t_stat_tip_perc_weekend_weekday:.3f}")
print(f"  P-value: {p_value_tip_perc_weekend_weekday:.3f}")

# Filter data for weekend Dinner only
weekend_dinner_df = df[(df['Day'].isin(['Sat', 'Sun'])) & (df['Time'] == 'Dinner')].copy()

# Perform independent samples t-test for Tip_Percentage_log by Smoker on Weekend Dinner
smoker_groups_tip_perc_weekend_dinner = [weekend_dinner_df['Tip_Percentage_log'][weekend_dinner_df['Smoker'] == smoker] for smoker in weekend_dinner_df['Smoker'].unique()]

# Check if there are at least 2 groups and enough data points in each for the test
if len(smoker_groups_tip_perc_weekend_dinner) == 2 and all(len(group) > 1 for group in smoker_groups_tip_perc_weekend_dinner):
    t_stat_smoker_tip_perc_weekend_dinner, p_value_smoker_tip_perc_weekend_dinner = stats.ttest_ind(*smoker_groups_tip_perc_weekend_dinner, equal_var=False) # Assuming unequal variances
    print(f"Independent samples t-test for Tip_Percentage_log by Smoker on Weekend Dinner:")
    print(f"  Test Statistic: {t_stat_smoker_tip_perc_weekend_dinner:.3f}")
    print(f"  P-value: {p_value_smoker_tip_perc_weekend_dinner:.3f}")
else:
    print("Not enough data to perform t-test for Tip_Percentage_log by Smoker on Weekend Dinner (might be only one or no smokers/non-smokers in this subset).")

# Filter data for weekends (Saturday and Sunday)
weekend_df = df[(df['Day'] == 'Sat') | (df['Day'] == 'Sun')].copy()

# 2. Independent samples t-test for Tip_Percentage_log by Time on Weekends
time_groups_tip_perc_weekend = [weekend_df['Tip_Percentage_log'][weekend_df['Time'] == time] for time in weekend_df['Time'].unique()]
if len(time_groups_tip_perc_weekend) == 2 and all(len(group) > 1 for group in time_groups_tip_perc_weekend):
    t_stat_time_tip_perc_weekend, p_value_time_tip_perc_weekend = stats.ttest_ind(*time_groups_tip_perc_weekend, equal_var=False) # Assuming unequal variances
    print(f"\n2. Independent samples t-test for Tip_Percentage_log by Time on Weekends:")
    print(f"  Test Statistic: {t_stat_time_tip_perc_weekend:.3f}")
    print(f"  P-value: {p_value_time_tip_perc_weekend:.3f}")
else:
    print("\n2. Not enough data to perform t-test for Tip_Percentage_log by Time on Weekends (might be only one time category on weekends).")

# 3. Independent samples t-test for Tip_Percentage_log by Smoker on Weekends
smoker_groups_tip_perc_weekend = [weekend_df['Tip_Percentage_log'][weekend_df['Smoker'] == smoker] for smoker in weekend_df['Smoker'].unique()]
if len(smoker_groups_tip_perc_weekend) == 2 and all(len(group) > 1 for group in smoker_groups_tip_perc_weekend):
    t_stat_smoker_tip_perc_weekend, p_value_smoker_tip_perc_weekend = stats.ttest_ind(*smoker_groups_tip_perc_weekend, equal_var=False) # Assuming unequal variances
    print(f"\n3. Independent samples t-test for Tip_Percentage_log by Smoker on Weekends:")
    print(f"  Test Statistic: {t_stat_smoker_tip_perc_weekend:.3f}")
    print(f"  P-value: {p_value_smoker_tip_perc_weekend:.3f}")
else:
    print("\n3. Not enough data to perform t-test for Tip_Percentage_log by Smoker on Weekends (might be only one smoker category on weekends).")

# 4. Independent samples t-test for Tip_Percentage_log by Gender on Weekends
gender_groups_tip_perc_weekend = [weekend_df['Tip_Percentage_log'][weekend_df['Gender'] == gender] for gender in weekend_df['Gender'].unique()]
if len(gender_groups_tip_perc_weekend) == 2 and all(len(group) > 1 for group in gender_groups_tip_perc_weekend):
    t_stat_gender_tip_perc_weekend, p_value_gender_tip_perc_weekend = stats.ttest_ind(*gender_groups_tip_perc_weekend, equal_var=False) # Assuming unequal variances
    print(f"\n4. Independent samples t-test for Tip_Percentage_log by Gender on Weekends:")
    print(f"  Test Statistic: {t_stat_gender_tip_perc_weekend:.3f}")
    print(f"  P-value: {p_value_gender_tip_perc_weekend:.3f}")
else:
    print("\n4. Not enough data to perform t-test for Tip_Percentage_log by Gender on Weekends (might be only one gender category on weekends).")

# 5. Pearson correlation test for Tip_Percentage_log and Partysize on Weekends
if len(weekend_df) > 1: # Ensure there's enough data for correlation
    corr_tip_perc_partysize_weekend, p_value_tip_perc_partysize_weekend = stats.pearsonr(weekend_df['Tip_Percentage_log'], weekend_df['Partysize'])
    print(f"\n5. Pearson correlation between Tip_Percentage_log and Partysize on Weekends:")
    print(f"  Correlation Coefficient: {corr_tip_perc_partysize_weekend:.3f}")
    print(f"  P-value: {p_value_tip_perc_partysize_weekend:.3f}")
else:
    print("\n5. Not enough data to perform correlation test for Tip_Percentage_log and Partysize on Weekends.")

# Filter data for weekends (Saturday and Sunday)
weekend_df = df[(df['Day'] == 'Sat') | (df['Day'] == 'Sun')].copy()

# Perform independent samples t-test for Tip_log by Time on Weekends
time_groups_tip_weekend = [weekend_df['Tip_log'][weekend_df['Time'] == time] for time in weekend_df['Time'].unique()]
# Check if there are at least 2 groups and enough data points in each
if len(time_groups_tip_weekend) == 2 and all(len(group) > 1 for group in time_groups_tip_weekend):
    t_stat_time_tip_weekend, p_value_time_tip_weekend = stats.ttest_ind(*time_groups_tip_weekend, equal_var=False) # Assuming unequal variances
    print(f"Independent samples t-test for Tip_log by Time on Weekends:")
    print(f"  Test Statistic: {t_stat_time_tip_weekend:.3f}")
    print(f"  P-value: {p_value_time_tip_weekend:.3f}")
else:
    print("Not enough data to perform t-test for Tip_log by Time on Weekends (might be only one time category on weekends).")

# Perform independent samples t-test for Amount_log by Time on Weekends
time_groups_amount_weekend = [weekend_df['Amount_log'][weekend_df['Time'] == time] for time in weekend_df['Time'].unique()]
if len(time_groups_amount_weekend) == 2 and all(len(group) > 1 for group in time_groups_amount_weekend):
    t_stat_time_amount_weekend, p_value_time_amount_weekend = stats.ttest_ind(*time_groups_amount_weekend, equal_var=False) # Assuming unequal variances
    print(f"\nIndependent samples t-test for Amount_log by Time on Weekends:")
    print(f"  Test Statistic: {t_stat_time_amount_weekend:.3f}")
    print(f"  P-value: {p_value_time_amount_weekend:.3f}")
else:
     print("\nNot enough data to perform t-test for Amount_log by Time on Weekends (might be only one time category on weekends).")

# Perform independent samples t-test for Tip_log by Gender on Weekends
gender_groups_tip_weekend = [weekend_df['Tip_log'][weekend_df['Gender'] == gender] for gender in weekend_df['Gender'].unique()]
if len(gender_groups_tip_weekend) == 2 and all(len(group) > 1 for group in gender_groups_tip_weekend):
    t_stat_gender_tip_weekend, p_value_gender_tip_weekend = stats.ttest_ind(*gender_groups_tip_weekend, equal_var=False) # Assuming unequal variances
    print(f"\nIndependent samples t-test for Tip_log by Gender on Weekends:")
    print(f"  Test Statistic: {t_stat_gender_tip_weekend:.3f}")
    print(f"  P-value: {p_value_gender_tip_weekend:.3f}")
else:
    print("\nNot enough data to perform t-test for Tip_log by Gender on Weekends (might be only one gender category on weekends).")


# Perform independent samples t-test for Amount_log by Gender on Weekends
gender_groups_amount_weekend = [weekend_df['Amount_log'][weekend_df['Gender'] == gender] for gender in weekend_df['Gender'].unique()]
if len(gender_groups_amount_weekend) == 2 and all(len(group) > 1 for group in gender_groups_amount_weekend):
    t_stat_gender_amount_weekend, p_value_gender_amount_weekend = stats.ttest_ind(*gender_groups_amount_weekend, equal_var=False) # Assuming unequal variances
    print(f"\nIndependent samples t-test for Amount_log by Gender on Weekends:")
    print(f"  Test Statistic: {t_stat_gender_amount_weekend:.3f}")
    print(f"  P-value: {p_value_gender_amount_weekend:.3f}")
else:
    print("\nNot enough data to perform t-test for Amount_log by Gender on Weekends (might be only one gender category on weekends).")



"""# Foodie's Business Expansion Analysis Report

## (a) Business Problem

Foodie's, a restaurant, is considering business expansion. To make informed decisions, they need to understand the key factors influencing customer spending and tipping behavior based on their existing transaction data.

## (b) Research Problem

What are the key characteristics of high-revenue and high-value customer interactions within the current business operations? Which variables show the strongest and most statistically significant associations with revenue (Amount) and tipping (Tip and Tip Percentage)?

## (c) Research Objective

The primary objective of this study is to leverage the provided transaction data to identify actionable insights and suggest practical business expansion strategies for Foodie’s management. This will be achieved by characterizing transactional and demographic variables, studying relationships between continuous variables, and comparing customer behavior across categorical groups.

## (d) Research Questions (RQs)

Based on the research objective, the following research questions guide the analysis:

**Descriptive RQs:**
* What is the trend in average spending across different days?
* What is the distribution of tip amounts and percentages?
* How does meal timing relate to average bill amounts?

**Inferential RQs:**
* How does party size relate to the bill amount and tip amount?
* Are differences in bill amounts across days statistically significant?
* Is there a statistically significant difference in bill amounts between lunch & dinner?
* Do smokers and non-smokers differ significantly in spending and tipping?
* Do male vs. female servers receive statistically different tip amounts? (Note: Server Gender data was not available in the provided dataset for direct testing).
* Are there significant differences in spending/tipping across days of the week?

## (e) Hypothesis (Mapped with Research Questions)

Here are the hypotheses tested, corresponding to the inferential research questions:

**Hypotheses on Transactional Drivers (Amount, Tip, and Party Size):**
* **RQ:** How strong is the relationship between bill amount, tip, and party size?
    * **H₀ (Null):** There is no linear correlation between party size and bill amount (or between bill amount and tip).
    * **H₁ (Alternative):** There is a significant linear correlation between party size and bill amount (or between bill amount and tip).

**Hypotheses on Operations Drivers (Meal Time, Smoker Status, Day of the Visit):**
* **RQ:** Are there significant differences in spending/tipping based on meal time, or smoker status?
    * **H₀ (Null):** There is no significant difference in the mean spending (or tip) between lunch and dinner / smokers and non-smokers.
    * **H₁ (Alternative):** There is a significant difference in the mean spending (or tip) between the groups.
* **RQ:** Are there significant differences in spending/tipping across days of the week?
    * **H₀ (Null):** There is no significant difference in the mean spending (or tip) across the different days of the week.
    * **H₁ (Alternative):** There is a significant difference in the mean spending (or tip) on at least one day compared to the others.

## (f) Section Wise Mention of Test and Analysis of Each Test

**Data Preparation and Transformation:**
* The data was loaded from the 'Serve (1).xlsx' file.
* Columns from 'Remark' onwards were dropped.
* 'Partysize' was converted to an integer type.
* 'Tip_Percentage' was calculated as (Tip / Amount) * 100.
* Natural log transformations were applied to 'Amount', 'Tip', and 'Tip_Percentage' to address skewness and better meet the assumptions of some statistical tests. The distributions of the log-transformed variables were visualized and their skewness calculated, showing improvement towards normality compared to the original data. Shapiro-Wilk tests confirmed that even after transformation, the distributions were still statistically significantly different from normal, which is a common observation in real-world data. However, the transformation improved the symmetry and reduced the impact of extreme values, making parametric tests more robust.

**Bivariate Analysis (Visualizations):**
* **Numerical vs. Numerical:** Scatter plots and a correlation matrix were generated for `Amount_log`, `Tip_log`, and `Partysize`.
    * **Analysis:** The scatter plots showed a positive trend between `Amount_log` and `Tip_log`, indicating that higher bills are generally associated with higher tips. The relationships between `Partysize` and the log-transformed amount and tip were weaker, with more dispersion, especially for larger party sizes. The correlation matrix confirmed a moderate positive correlation between `Amount_log` and `Tip_log` (r ~ 0.57) and weak positive correlations between `Partysize` and both `Amount_log` (r ~ 0.15) and `Tip_log` (r ~ 0.18).
* **Numerical vs. Categorical:** Boxplots and violin plots were created to compare the distributions of `Amount_log` and `Tip_log` across 'Gender', 'Smoker', 'Day', and 'Time'.
    * **Analysis:** Visual inspection suggested potential differences in spending and tipping based on 'Smoker' status, 'Day' of the week, and 'Time' of day (Lunch vs. Dinner). 'Gender' appeared to have less of a noticeable impact on the distributions of log-transformed amounts and tips. Dinner times visually showed higher median log-transformed amounts and tips compared to Lunch. Variations were also observed across different days.

**Statistical Testing and Analysis:**

* **Correlation Tests (Amount_log/Tip_log vs Partysize):**
    * **Test:** Pearson correlation tests were performed between `Amount_log` and `Partysize`, and `Tip_log` and `Partysize`.
    * **Analysis:** Both tests yielded statistically significant positive correlations (p < 0.05).
        * `Amount_log` vs. `Partysize`: r = 0.151, p = 0.004.
        * `Tip_log` vs. `Partysize`: r = 0.180, p = 0.001.
    * **Implication:** While the correlation coefficients are weak, these significant p-values indicate that there is a statistically discernible tendency for larger parties to be associated with slightly higher log-transformed bill amounts and tips. Larger groups, therefore, contribute more in absolute terms.

* **Group Differences (Amount_log by Categorical Variables):**
    * **Test:** Independent samples t-tests were conducted for `Amount_log` by 'Gender', `Amount_log` by 'Smoker', and `Amount_log` by 'Time'. A one-way ANOVA was performed for `Amount_log` by 'Day'.
    * **Analysis:**
        * `Amount_log` by Gender: p = 0.370. Not statistically significant.
        * `Amount_log` by Smoker: p = 0.232. Not statistically significant.
        * `Amount_log` by Time: p = 0.079. Not statistically significant at the 0.05 level.
        * `Amount_log` by Day (ANOVA): p = 0.010. Statistically significant.
    * **Implication:** There is no statistically significant evidence, based on this analysis of mean log-transformed amount, that average bill amount per person differs based on Gender, Smoker status, or Time of day (Lunch vs. Dinner). However, the statistically significant ANOVA for 'Day' indicates that the average bill amount *does* vary significantly across the different days of the week.

* **Group Differences (Tip_log by Categorical Variables):**
    * **Test:** Independent samples t-tests were conducted for `Tip_log` by 'Gender', `Tip_log` by 'Smoker', and `Tip_log` by 'Time'. A one-way ANOVA was performed for `Tip_log` by 'Day'.
    * **Analysis:**
        * `Tip_log` by Gender: p = 0.408. Not statistically significant.
        * `Tip_log` by Smoker: p = 0.545. Not statistically significant.
        * `Tip_log` by Time: p = 0.042. Statistically significant.
        * `Tip_log` by Day (ANOVA): p = 0.030. Statistically significant.
    * **Implication:** Similar to bill amount, there's no statistically significant difference in average log-transformed tip based on Gender or Smoker status. However, there is a statistically significant difference in average log-transformed tip between Lunch and Dinner, with Dinner likely having higher tips. The significant ANOVA for 'Day' also indicates that average tip varies significantly across the days of the week.

* **Specific Day Comparisons (Amount_log/Tip_log):**
    * **Test:** Independent samples t-tests were performed to compare `Amount_log` and `Tip_log` between Saturday and Sunday, and between Weekend (Sat/Sun) and Weekdays.
    * **Analysis:**
        * `Amount_log` Sat vs Sun: p = 0.100. Not statistically significant.
        * `Tip_log` Sat vs Sun: p = 0.047. Statistically significant. Sunday has significantly higher tips than Saturday.
        * `Amount_log` Weekend vs Weekdays: p = 0.006. Statistically significant. Weekends have significantly higher bill amounts than weekdays.
        * `Tip_log` Weekend vs Weekdays: p = 0.026. Statistically significant. Weekends have significantly higher tips than weekdays.
    * **Implication:** Weekends are significantly more profitable in terms of both bill amount and tips compared to weekdays. Within the weekend, Sunday stands out for having significantly higher tips than Saturday.

* **Weekend Specific Analysis (Amount/Tip/Tip Percentage by Smoker/Time/Gender/Partysize):**
    * **Test:** Several t-tests and a Pearson correlation were performed on the weekend subset of the data.
    * **Analysis:**
        * Amount by Smoker on Weekends (Original): p = 0.036. Statistically significant difference. Smoker status impacts bill amount on weekends.
        * Tip by Smoker on Weekends (Original): p = 0.352. Not statistically significant.
        * Tip Percentage log by Smoker on Weekend Dinner: p = 0.012. Statistically significant difference. Smoker status impacts tip percentage specifically during Weekend Dinner.
        * Tip Percentage log by Smoker on Weekends: p = 0.013. Statistically significant difference. Smoker status impacts tip percentage on weekends overall.
        * Tip Percentage log by Time on Weekends: p = 0.264. Not statistically significant.
        * Tip Percentage log by Gender on Weekends: p = 0.597. Not statistically significant.
        * Tip Percentage log and Partysize on Weekends: p = 0.874. Not statistically significant correlation.
        * Tip log by Time on Weekends: p = 0.829. Not statistically significant.
        * Amount log by Time on Weekends: p = 0.196. Not statistically significant.
        * Tip log by Gender on Weekends: p = 0.812. Not statistically significant.
        * Amount log by Gender on Weekends: p = 0.768. Not statistically significant.
    * **Implication:** On weekends, smoker status has a significant impact on the original bill amount and the log-transformed tip percentage. This suggests smokers might spend more on average or tip a higher percentage on weekends, particularly during dinner. Other factors like time, gender, and party size do not show a statistically significant impact on log-transformed tip percentage during weekends.

## (g) Recommendations

Based on the comprehensive analysis of the data, the following recommendations are provided for Foodie's business expansion:

1.  **Capitalize on Weekend Peak Performance:** Weekends are the most lucrative period, with significantly higher average bills and tips than weekdays. Expansion strategies should prioritize maximizing weekend business. This could involve:
    *   Expanding capacity or opening new locations in areas with high weekend foot traffic.
    *   Developing premium weekend menus, specials, or experiences to encourage higher spending.
    *   Ensuring optimal staffing levels and service quality on Saturdays and Sundays.

2.  **Optimize the Dinner Experience:** Dinner time is associated with significantly higher average tips, even if the average bill amount per person isn't statistically different from lunch. Focus on enhancing the dinner service to maintain and potentially increase this value.

3.  **Investigate Smoker Behavior on Weekends:** The finding that smoker status significantly impacts bill amount and tip percentage on weekends (especially at dinner) warrants further investigation. Understanding *why* this difference exists (e.g., longer stays, higher alcohol consumption, specific group dynamics) could reveal targeted marketing or service opportunities for this segment on weekends.

4.  **Deep Dive into Day-Specific Revenue Drivers:** While the ANOVA shows significant differences across days, further post-hoc analysis is needed to identify exactly which days are significantly different from each other beyond the weekend/weekday split. This granular understanding can inform targeted promotions or operational adjustments for specific days.

5.  **Strategize to Increase Average Bill Value:** The moderate positive correlation between bill amount and tip highlights the importance of increasing the average check size. Train staff on effective upselling techniques and promote high-margin menu items.

6.  **Consider Party Size in Capacity and Service:** While party size has a weak correlation, larger parties contribute more in total revenue and tip. Ensure the restaurant can comfortably accommodate larger groups, especially on peak days and times.

7.  **Utilize Data for Targeted Marketing:** Use the insights about high-performing days (weekends, particularly Sunday for tips) and times (Dinner) to inform marketing campaigns and promotions.

8.  **Implement Continuous Monitoring:** Regularly analyze sales and tipping data, broken down by the identified key factors (Day, Time, and potentially Smoker status on weekends), to track the effectiveness of implemented strategies and adapt to changing customer trends.

By focusing on these statistically supported insights and recommendations, Foodie's management can make more strategic and data-driven decisions regarding business expansion and operational improvements, aiming to maximize revenue and profitability.

## (h) Source Codes
"""

import scipy.stats as stats

# Calculate Pearson correlation and p-value for Amount and Tip
corr_amount_tip, p_value_amount_tip = stats.pearsonr(df['Amount'], df['Tip'])

print(f"Pearson correlation between Amount and Tip (Original):")
print(f"  Correlation Coefficient: {corr_amount_tip:.3f}")
print(f"  P-value: {p_value_amount_tip:.3f}")

# Calculate Pearson correlation and p-value for Amount_log and Tip_log
corr_amount_log_tip_log, p_value_amount_log_tip_log = stats.pearsonr(df['Amount_log'], df['Tip_log'])

print(f"\nPearson correlation between Amount_log and Tip_log (Log-transformed):")
print(f"  Correlation Coefficient: {corr_amount_log_tip_log:.3f}")
print(f"  P-value: {p_value_amount_log_tip_log:.3f}")

